### ISSUE TITLE
URL escaping doesn't work properly (is it needed?)

### ISSUE THREAD

**Issue by ichesnokov** [jhthorsen/cloudinary#3]
String of parameters like`tags=66e29431-863b-4ccd-8de2-426005f051b8,123.456&timestamp=1505413480` gets URL-escaped and Cloudinary doesn't recognise it, saying that the original string should be signed, not the escaped one. In particular comma gets escaped - this is not needed.

**Comment by jhthorsen** [comment]
Do you have time to write a test and submit a pull request with fix?

**Comment by evoyy** [comment]
This issue can be closed. Resolved by https://github.com/jhthorsen/cloudinary/pull/5
